"""Public kernel contracts for orcha-agent plugins."""

from .events import (
    AgentBuildAfter,
    AgentBuildBefore,
    AppExit,
    AppStart,
    Event,
    EventBus,
    EventHandlerRegistration,
    InterruptRaised,
    ModelChunk,
    ModelSwitch,
    SessionSwitch,
    ToolCallEnd,
    ToolCallStart,
    TurnEnd,
    TurnStart,
)
from .plugin import Handled, ModeSpec, PluginAPI, PluginSpec, ProviderCaps, Resolved
from .registry import (
    BackendRegistration,
    CommandRegistration,
    MiddlewareRegistration,
    PromptFragment,
    ProviderRegistration,
    Registry,
    RendererRegistration,
    SubagentRegistration,
)

__all__ = [
    "AgentBuildAfter",
    "AgentBuildBefore",
    "AppExit",
    "AppStart",
    "BackendRegistration",
    "CommandRegistration",
    "Event",
    "EventBus",
    "EventHandlerRegistration",
    "Handled",
    "InterruptRaised",
    "MiddlewareRegistration",
    "ModeSpec",
    "ModelChunk",
    "ModelSwitch",
    "PluginAPI",
    "PluginSpec",
    "PromptFragment",
    "ProviderCaps",
    "ProviderRegistration",
    "Registry",
    "RendererRegistration",
    "Resolved",
    "SessionSwitch",
    "SubagentRegistration",
    "ToolCallEnd",
    "ToolCallStart",
    "TurnEnd",
    "TurnStart",
]
